from datetime import date
from sqlalchemy.orm import Session
from myapi.domain.market_analysis.market_analysis_model import AiAnalysisModel
from myapi.domain.market_analysis.market_analysis_schema import (
    AiAnalysisVO,
    MarketAnalysis,
)


class MarketAnalysisRepository:
    def __init__(self, db_session: Session):
        self.db_session = db_session

    def get_by_date(self, analysis_date: date) -> AiAnalysisVO | None:
        return (
            self.db_session.query(AiAnalysisModel)
            .filter(AiAnalysisModel.date == analysis_date.strftime("%Y-%m-%d"))
            .first()
        )

    def create(
        self, analysis_date: date, analysis_data: MarketAnalysis
    ) -> AiAnalysisVO:
        db_analysis = AiAnalysisVO(
            id=None,  # ID will be auto-generated by the database
            date=analysis_date.strftime("%Y-%m-%d"),
            value=analysis_data.model_dump(mode="json"),
        )
        self.db_session.add(db_analysis)
        self.db_session.commit()
        self.db_session.refresh(db_analysis)
        return db_analysis
